name: "worksafenpm2"
on: workflow_dispatch

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_PROVIDER: 'sumgithub'
      PLATFORM_REPO: 'worksafe-npm-virt'
      BUILD_NAME: "worksafe-npm-build"
      BUILD_ID: "${{github.run_number}}"

     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: https://psemea.jfrog.io
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}


       - name: Set CLI Config
         run: jf npm-config --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO

       - name: Run Audit scan for the git workspace
         run: jf audit --watches worksafe-sec-watch --fail=true
 
       - name: Install Dependencies
         run: jf npm install --build-name=${{env.BUILD_NAME}} --build-number=${{env.BUILD_ID}}
         
       - name: Publish
         run: jf npm publish --build-name=${{env.BUILD_NAME}} --build-number=${{env.BUILD_ID}} --project=worksafeperm

         
       - name: Collect Build info details
         run: |
          # Collect environment variables for the build
          jf rt bce ${{env.BUILD_NAME}} ${{ github.run_number }} --project=worksafeperm
          # Collect VCS details from git and add them to the build
          jf rt build-add-git ${{env.BUILD_NAME}} ${{ github.run_number }} --project=worksafeperm
       
       - name: Publish build-info to Artifactory
         run: |
          jf rt bp ${{env.BUILD_NAME}} ${{ github.run_number }} --project=worksafeperm
          
       - name: Perform build scan
         run: |   
          jf bs ${{env.BUILD_NAME}} ${{ github.run_number }}
